version: '3.1'
services:
  jupyter:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/home/jovyan/
    ports:
      - 8888:8888
  db:
    container_name: leccion4-postgres2
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_user: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eipdb
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    container_name: leccion4-adminer2
    restart: always
    ports:
      - 8080:8080
  mongo:
    container_name: leccion5-mongo2
    image: mongo:latest
    command: 
      - --bind_ip_all
    ports:
      - '27017:27017'